---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r filter data, include = FALSE}
data(instacart) 

cleaned_data = 
  instacart %>% 
  mutate(department = factor(department)) %>% 
  filter(
         user_id %in% 1:500,
         !is.na(department),
         !is.na(aisle),
         !is.na(order_hour_of_day)
         )
```


             
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
cleaned_data %>% 
  count(aisle, department) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~department, type = "bar", colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
cleaned_data %>%  
  mutate(department = fct_reorder(department, order_hour_of_day)) |> 
  plot_ly(y = ~order_hour_of_day, color = ~department, type = "box", colors = "viridis") 
```

### Chart C

```{r}
cleaned_data %>%  
  mutate(text_label = str_c("Aisle: ", aisle, "Dept: ", department)) %>%
  count(aisle, department, text_label) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(
    x = ~department, y = ~n, type = "scatter", mode = "markers",
    color = ~department, text = ~text_label, alpha = 0.5, 
    colors = scales::viridis_pal()(length(unique(cleaned_data$department))))
```


